package la.ipo.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.display_name
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.email
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.password
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.mobile
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.area_code
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id_type
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private Byte idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id_no
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.status
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_type
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_datetime
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.update_datetime
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.display_name
     *
     * @return the value of tbl_user.display_name
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.display_name
     *
     * @param displayName the value for tbl_user.display_name
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.email
     *
     * @return the value of tbl_user.email
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.email
     *
     * @param email the value for tbl_user.email
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.password
     *
     * @return the value of tbl_user.password
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.password
     *
     * @param password the value for tbl_user.password
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.mobile
     *
     * @return the value of tbl_user.mobile
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.mobile
     *
     * @param mobile the value for tbl_user.mobile
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.area_code
     *
     * @return the value of tbl_user.area_code
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.area_code
     *
     * @param areaCode the value for tbl_user.area_code
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id_type
     *
     * @return the value of tbl_user.id_type
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public Byte getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id_type
     *
     * @param idType the value for tbl_user.id_type
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setIdType(Byte idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id_no
     *
     * @return the value of tbl_user.id_no
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id_no
     *
     * @param idNo the value for tbl_user.id_no
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.status
     *
     * @return the value of tbl_user.status
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.status
     *
     * @param status the value for tbl_user.status
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_type
     *
     * @return the value of tbl_user.user_type
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_type
     *
     * @param userType the value for tbl_user.user_type
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_datetime
     *
     * @return the value of tbl_user.create_datetime
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_datetime
     *
     * @param createDatetime the value for tbl_user.create_datetime
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.update_datetime
     *
     * @return the value of tbl_user.update_datetime
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.update_datetime
     *
     * @param updateDatetime the value for tbl_user.update_datetime
     *
     * @mbggenerated Wed Apr 02 17:03:04 CST 2014
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}